### ISSUE TITLE
"a MariaDB server" should be "a Solr server"

### ISSUE THREAD

**Issue by ikandars** [bitnami/bitnami-docker-solr#16]
I found `a MariaDB server` sentence in readme file which I believe it should be `a Solr server`

**Comment by javsalgar** [comment]
Hi,

Thanks for reporting. I already push the change, it should be available very soon.

**Comment by javsalgar** [comment]
Fixed https://github.com/bitnami/bitnami-docker-solr/commit/9a0be8885f22c67336dd7431c66baa964e6dd0f9#diff-04c6e90faac2675aa89e2176d2eec7d8
