### ISSUE TITLE
SOLR_HEAP environment variable ignored

### ISSUE THREAD

**Issue by mssc-hoffleit** [bitnami/bitnami-docker-solr#21]
**Description:**

Environment variable SOLR_HEAP ignored when specified.

Steps to reproduce the issue:

    # docker run --name solr --env SOLR_HEAP=2g bitnami/solr
    # docker exec solr ps auxf

**Describe the results you received:**

    USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
    solr       259  0.0  0.0   7640  2600 ?        Rs   14:34   0:00 ps auxf
    solr         1  0.0  0.0   2280   712 ?        Ss   14:33   0:00 tini -- /run.sh
    solr        25  0.0  0.0   2328   744 ?        S    14:33   0:00 tail -f /opt/bitnami/solr/logs/solr.log
    solr        78 30.1  4.2 5524224 691200 ?      Sl   14:33   0:08 /opt/bitnami/java/bin/java -server -Xms512m -Xmx512m -XX:+UseG1GC -XX:+PerfDisableSharedMem -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=250 -XX:+UseLargePages -XX:+AlwaysPreTouch -verbose:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -Xloggc:/opt/bitnami/solr/logs/solr_gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=9 -XX:GCLogFileSize=20M -Dsolr.jetty.inetaccess.includes= -Dsolr.jetty.inetaccess.excludes= -Dsolr.log.dir=/opt/bitnami/solr/logs -Djetty.port=8983 -DSTOP.PORT=7983 -DSTOP.KEY=solrrocks -Duser.timezone=UTC -Djetty.home=/opt/bitnami/solr/server -Dsolr.solr.home=/opt/bitnami/solr/server/solr -Dsolr.data.home= -Dsolr.install.dir=/opt/bitnami/solr -Dsolr.default.confdir=/opt/bitnami/solr/server/solr/configsets/_default/conf -Xss256k -Dsolr.jetty.https.port=8983 -Dsolr.log.muteconsole -XX:OnOutOfMemoryError=/opt/bitnami/solr/bin/oom_solr.sh 8983 /opt/bitnami/solr/logs -jar start.jar --module=http

**Describe the results you expected:**

I would have expected to see the Solr process running with "-Xms2g -Xmx2g", as it is the case with the official Solr docker image (docker-solr).

**Comment by miguelaeh** [comment]
Hi @mssc-hoffleit ,
Thank you very much for your request, we will create a task on our side to evaluate it.
We will update this thread when we have news.
Regards.
