### ISSUE TITLE
Is it feasible for the standard Solr docker image to include the jts-core library?

### ISSUE THREAD

**Issue by ejschoen** [bitnami/bitnami-docker-solr#27]
**Description**

It's not possible to use SpatialRecursivePrefixTreeField out of the box.  The jts-core-1.15.0.jar file must be added to /opt/solr/server/solr-webapp/webapp/WEB-INF/lib.  But with increasingly secure Solr container deployments (/opt/solr/server is owned by root, but the image runs under a non-privileged user in many deployments), it's not possible to merge the library in at startup time, for example with a script in /docker-entrypoint-initdb.d.  

**Steps to reproduce the issue:**

1. Create a core or a collection with schema with a field whose class is "solr.SpatialRecursivePrefixTreeFieldType" and spatialContextFactory is "JTS."
2. Try to load the core or collection. It will fail.
3. Try to copy jts-core-1.15.0.jar into /opt/solr/server/solr-webapp/webapp/WEB-INF/lib in a script in /docker-entrypoint-initdb.d.  It will fail with permission denied until running as uid 0.
4. Try to use gosu to copy the file.  Permission will be denied.

**Additional information you deem important:**

Of course it's always possible to build a custom image that overlays jts-core, but then it would be necessary to keep the custom image fresh with respect to releases from Apache and Bitnami.   

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:23 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 27
  Paused: 0
  Stopped: 6
 Images: 39
 Server Version: 19.03.12
 Storage Driver: aufs
  Root Dir: ******
  Backing Filesystem: extfs
  Dirs: 512
  Dirperm1 Supported: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: 5wz828g78s887u4r8z6s774fw
  Is Manager: true
  ClusterID: fpxuwe6ckjtdy029zvovuxhg8
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.0.200
  Manager Addresses:
   192.168.0.200:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-8-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.79GiB
 Name: ******
 ID: IL7P:6WKF:3DK2:PVFQ:Z3MY:GAW3:COYI:5CUO:X2BM:NN7T:WO3C:B22P
 Docker Root Dir: *******
 Debug Mode: false
 Username: ******
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  192.168.0.200:5000
  localhost:5000
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
I see your point, I will create an internal task to evaluate it, but it will depend on other priorities that the team has, because of that, I can't provide you an ETA. In the meantime, you can use the proposed workaround to extend the current image.

**Comment by MurzNN** [comment]
Is there any progress with this task? I'm tinkering with the same problem...

**Comment by carrodher** [comment]
Unfortunately, if this task was not done during this time it's because after evaluating it, it has not been given sufficient priority with respect to other tasks that the team has been working on.

If you would like to contribute by adding this feature, the Bitnami team will be happy to review any PR and provide feedback. [Here](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md) you can find the contributing guidelines.
Otherwise, I'm sorry to say that if it hasn't been implemented during this time, I don't think it will be done in the near future.

**Comment by MurzNN** [comment]
bump!
