### ISSUE TITLE
JVM Memory Settings - how can I change them?

### ISSUE THREAD

**Issue by rmuehlbauer** [bitnami/bitnami-docker-solr#30]
**Description**

I'm using the bitnami/solr helm chart to run solr on a kubernetes environment.
The docker image I'm using is bitnami/solr:8.9.0-debian-10-r5
In the helm chart, there is an option called "javaMem" which is - according to the docs - used to pass memory parameter to the JVM.
I think the helm/kubernetes part is working - any values I put there, end up as a ENV variable called SOLR_JAVA_MEM in the running solr docker container.
The JVM just is not aware of those Mem Parameters...

The problem seems to be, that the bitnami/solr docker container itself just does not use the env variable for mem settings.
I think the script responsible for doing solr related environment stuff is /opt/bitnami/scripts/solr-env.sh and it just does not care about the SOLR_JAVA_MEM environment variable...
How is this intended to work?
How can I tweak JVM Mem Settings?

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

I've also opened a issue in the helm chart section - [Issue 6812](https://github.com/bitnami/charts/issues/6812) - I'm just not sure, where this issue really belongs to

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
GKE

**Comment by migruiz4** [comment]
Duplicated of https://github.com/bitnami/charts/issues/6812
