### ISSUE TITLE
Core not created with SOLR_CORE & SOLR_CORE_CONF_DIR 

### ISSUE THREAD

**Issue by RoSk0** [bitnami/bitnami-docker-solr#31]
**Description**

Solr core not created with SOLR_CORE & SOLR_CORE_CONF_DIR  environment variables.

**Steps to reproduce the issue:**

1. Pull latest image
    ```
    $ docker pull bitnami/solr:8
    Digest: sha256:95ba862d7979fe139a314d666e63dad9253e747d4087d6070c5e876357476b2f
    Status: Downloaded newer image for bitnami/solr:8
    docker.io/bitnami/solr:8
    ```

2. Start a container by mounting in core config directory ( attached for reproducing simplicity ) and specifying core name and path to the config directory via variables:
    ```
    $ docker run -it --rm -v $(pwd)/config/:/config -p 8983:8983 -e SOLR_CORE=drupal -e SOLR_CORE_CONF_DIR=/config bitnami/solr:8
    ```
3. Wait for it to start
4. In the other terminal query the status of ALL cores
    ```
    $ curl http://localhost:8983/solr/admin/cores?action=STATUS
    {
      "responseHeader":{
        "status":0,
        "QTime":30},
      "initFailures":{},
      "status":{}}
    ```

**Describe the results you received:**

No cores was created

**Describe the results you expected:**

Core with the name `drupal` created.

Like this. Lets mount in `libsolr.sh` with the proper error handling:
```
$ docker run -it --rm -v $(pwd)/config/:/config -v $(pwd)/libsolr-proof.sh:/opt/bitnami/scripts/libsolr.sh -p 8983:8983 -e SOLR_CORE=drupal -e SOLR_CORE_CONF_DIR=/config bitnami/solr:8
...
solr 04:40:57.74 ERROR ==> There was an error when creating the core
```

That's better!!!

Now lets fix it completely.

```
$ docker run -it --rm -v $(pwd)/config/:/config -v $(pwd)/libsolr-fixed.sh:/opt/bitnami/scripts/libsolr.sh -p 8983:8983 -e SOLR_CORE=drupal -e SOLR_CORE_CONF_DIR=/config bitnami/solr:8

Looking better now. You can notice that there is more output. Lets query core status:
$ curl http://localhost:8983/solr/admin/cores?action=STATUS
{
  "responseHeader":{
    "status":0,
    "QTime":4},
  "initFailures":{},
  "status":{
    "drupal":{
      "name":"drupal",
      "instanceDir":"/opt/bitnami/solr/server/solr/drupal",
      "dataDir":"/opt/bitnami/solr/server/solr/drupal/data/",
      "config":"solrconfig.xml",
      "schema":"schema.xml",
      "startTime":"2021-07-23T04:42:19.782Z",
      "uptime":9723,
      "index":{
        "numDocs":0,
        "maxDoc":0,
        "deletedDocs":0,
        "indexHeapUsageBytes":0,
        "version":2,
        "segmentCount":0,
        "current":true,
        "hasDeletions":false,
        "directory":"org.apache.lucene.store.NRTCachingDirectory:NRTCachingDirectory(MMapDirectory@/bitnami/solr/server/solr/drupal/data/index lockFactory=org.apache.lucene.store.NativeFSLockFactory@18916078; maxCacheMB=48.0 maxMergeSizeMB=4.0)",
        "segmentsFile":"segments_1",
        "segmentsFileSizeInBytes":69,
        "userData":{},
        "sizeInBytes":69,
        "size":"69 bytes"}}}}
```

** Bug reason and how to fix:**

There is actually two bugs here and this is probably why the issue went unnoticed.

1. CURL command that creates core doesn't check the response status code. At the moment Solr returns 400 when
   `solr_create_core()` tries to create a core with a cryptic message about duplicated config files but, see next
2. Location of the configuration files copied from  `SOLR_CORE_CONF_DIR` is wrong - they are placed into `instanceDir`
   when they should be in the `conf` which is child of the `instanceDir`. See the warning in the CREATE command 
   description section <https://solr.apache.org/guide/8_9/coreadmin-api.html#coreadmin-create>

**Comment by miguelaeh** [comment]
Hi @RoSk0 ,
Thank you very much for debugging the error and for creating a PR fixing it. We will take a look at the PR and continue the conversation there.

**Comment by RoSk0** [comment]
What a speed, thanks.
