### ISSUE TITLE
Add Documentation for SOLR_OPTS variable

### ISSUE THREAD

**Issue by devtype** [bitnami/bitnami-docker-solr#43]
**Description**
I tried to start my Solr with additional arguments in my case -XX:G1HeapRegionSize, -XX:+AggressiveOpts and some args for new_relic. I tried to alter the docker image until I realised it is possible to set SOLR_OPTS in the docker-compose.yml

 Extend Documentation and describe how to set additional solr arguments in docker-compose
`
    environment:
      SOLR_OPTS: '${SOLR_OPTS}'`

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback! As you spotted the missing documentation item, would you like to contribute with a PR?

**Comment by javsalgar** [comment]
Awesome! :D

**Comment by devtype** [comment]
I have created the pull-request https://github.com/bitnami/bitnami-docker-solr/pull/44

**Comment by javsalgar** [comment]
Thank you!

**Comment by carrodher** [comment]
Closing this issue since the associated PR was merged
