### ISSUE TITLE
Upgrade to JDK 11

### ISSUE THREAD

**Issue by tenaciousRas** [bitnami/bitnami-docker-solr#45]
### Name and Version

bitnami/solr:8.11.1

### What is the problem this feature will solve?

Some improvements in Java 10+ made to improve JVM resource management (ram, cpu) running under Docker are not to be backported to Java 8. It might be nice to use features like -XX:+UseContainerSupport, -XX:MaxRAMPercentage.

### What is the feature you are proposing to solve the problem?

Upgrade JVM rte.

### What alternatives have you considered?

Build my own image for SOLR 8 + JDK 11.

**Comment by miguelaeh** [comment]
Hi @tenaciousRas ,
We basically ship Java 8 because it is the version Solr guarantees on their tests: https://solr.apache.org/guide/8_11/solr-system-requirements.html#java-and-lucenesolr-combinations

You can always change the Dockerfile to install the version you require.
