### ISSUE TITLE
arm64/v8 (M1 compatible) images

### ISSUE THREAD

**Issue by orangewolf** [bitnami/bitnami-docker-solr#46]
### Name and Version

bitnami/solr:latest

### What is the problem this feature will solve?

This image is not very stable / reliable on an M1 Mac and will not run on G type AWS instances. The ARM version of the official solr image does run in those environments well, but does not have some of the awesome configurability of the Bitnami image (great work btw)

### What is the feature you are proposing to solve the problem?

Build and push an image for ARM to docker hub.

### What alternatives have you considered?

I may try to build my own if needed, but it seemed worth asking if you had plans to build one before I embarked on that journey.

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.

**Comment by orangewolf** [comment]
thank you, I just found that issue a few minutes ago. I understand that it is quite the undertaking.
