### ISSUE TITLE
Uploading custom config set via zookeper

### ISSUE THREAD

**Issue by leonidUH** [bitnami/bitnami-docker-solr#47]
### Name and Version

bitnami/solr:8.11.1

### What steps will reproduce the bug?

1 prepare custom config set (CS)
2. upload it via zookeeper
     `/opt/bitnami/solr/bin/solr zk upconfig -n {CS_NAME} -d  {CS_FOLDER} -z {ZK_HOST}:2181`
3 create collection with this config set
```
   https://{SOLR_HOST}:8983/solr/admin/collections?action=CREATE&name= 
  {COLLECTION_NAME}&numShards=1&replicationFactor=1&maxShardsPerNode=1&collection.configName={CS_NAME}&wt=json
```

### What is the expected behavior?

expected behavior that after I upload a custom config set - I can create new collections with it 

### What do you see instead?

I see that `solr zk upconfig` upload it to path  `/configs/{CS_NAME}` but bitnami solr using `/solr/configs/{CS_NAME}` path on zookeeper.
Because this when I execute solr create a collection - I got error: `Can not find the specified config set : {CS_NAME}`

**Comment by fmulero** [comment]
Hi @leonidUH Sorry for my very late response, I missed the notification.

You can upload the configset to the `/solr` directory in zookeeper appending the path to the `-z` parameter:

```
/opt/bitnami/solr/bin/solr zk upconfig -n {CS_NAME} -d {CS_FOLDER} -z {ZK_HOST}:2181/solr
```

**Comment by leonidUH** [comment]
@fmulero thank you
