### ISSUE TITLE
Default SOLR_ADMIN_USERNAME/SOLR_ADMIN_PASSWORD doesn't work

### ISSUE THREAD

**Issue by jinshen1983** [bitnami/bitnami-docker-solr#50]
### Name and Version

bitnami/solr:8

### What steps will reproduce the bug?

```
$ curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-solr/master/docker-compose.yml > docker-compose.yml
$ docker-compose up -d
```
Using the above command to start the container, requires a username/password to login.
http://localhost:8983/solr/#/login

But the default username/password doesn't work.

Even if I set `SOLR_ENABLE_AUTHENTICATION` to `no` in `docker-compose.yml`, it still requires a username/password to log in.

### What is the expected behavior?

Can successfully log into Solr Dashboard with default username/password.

Or view the dashboard without username/password if disabling authentication.

### What do you see instead?

Always requires username/password

**Comment by javsalgar** [comment]
Hi,

Thank you so much for reporting, it seems there is a typo and the password should be `bitnami`, not `Bitnami`. It worked for me.

<img width="875" alt="image" src="https://user-images.githubusercontent.com/1133777/167811087-1c87aceb-f352-4ecb-a29f-6e22537827dc.png">
